@startuml

participant "Client 1" as client1
participant "Server" as server
participant "Client 2" as client2

== Join the server ==

note right of client1
The socket is instanciated and the connection is
automatically etablished.
end note

client1->server : Establish connection
server<-->client1 : Connection established
server->client1 : INIT <height> <widht> <winLenght>

client2->server : Establish connection
server<-->client2 : Connection established
server->client2 : INIT <height> <widht> <winLenght>

== Invalid entry example ==

note right of client1
Let's admit that the gameboard
is a 8x8 board
end note

client1->server : PLACE -1
server->client1 : ERROR 1

client1->server : PLACE A
server->client1 : ERROR 2

client1->server : PLACE 10
server->client1 : ERROR 1

note right of client1
Let's admit that the gameboard
column 2 is full.
end note

client1->server : PLACE 2
server->client1 : ERROR 3

== Invalid command example ==

client1->server : HELLO WORLD
server->client1 : ERROR -1

@enduml